services:
  - type: web
    name: starlink-monitor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn starlink_map:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: IS_RENDER
        value: true 